In [ ]:
# databricks-connect automatically adds the project root to the PYTHONPATH, so we can import modules from src
# But when running this script on Databricks Workspace, we need to add the project root to the PYTHONPATH manually
# import os
# import sys

# current_dir = os.getcwd()
# parent_dir = os.path.abspath(os.path.join(current_dir, "..", "..", ".."))
# sys.path.append(parent_dir)

In [ ]:
from citibike.citibike_utils import get_trip_duration_mins
from utils.datetime_utils import timestamp_to_date_col

from pyspark.sql.functions import create_map, lit

In [ ]:
pipeline_id = dbutils.widgets.get("pipeline_id")
run_id = dbutils.widgets.get("run_id")
task_id = dbutils.widgets.get("task_id")
processed_timestamp = dbutils.widgets.get("processed_timestamp")

catalog = dbutils.widgets.get("catalog")

In [ ]:
df = spark.read.table(f"{catalog}.01_bronze.jc_citibike")

In [ ]:
# display(df.limit(5))

DataFrame[ride_id: string, rideable_type: string, started_at: timestamp, ended_at: timestamp, start_station_name: string, start_station_id: string, end_station_name: string, end_station_id: string, start_lat: decimal(10,0), start_lng: decimal(10,0), end_lat: decimal(10,0), end_lng: decimal(10,0), member_casual: string, metadata: map<string,string>]

In [ ]:
df = get_trip_duration_mins(spark, df, "started_at", "ended_at", "trip_duration_mins")

In [ ]:
# display(df.select("started_at", "ended_at", "trip_duration_mins").limit(5))

DataFrame[started_at: timestamp, ended_at: timestamp, trip_duration_mins: double]

In [10]:
df = timestamp_to_date_col(spark, df, "started_at", "trip_start_date")

In [ ]:
# display(df.select("started_at", "trip_start_date").limit(5))

DataFrame[started_at: timestamp, trip_start_date: date]

In [ ]:
df = df.withColumn(
    "metadata",
    create_map(
        lit("pipeline_id"),
        lit(pipeline_id),
        lit("run_id"),
        lit(run_id),
        lit("task_id"),
        lit(task_id),
        lit("processed_timestamp"),
        lit(processed_timestamp),
    ),
)

In [13]:
df = df.select(
    "ride_id",
    "trip_start_date",
    "started_at",
    "ended_at",
    "start_station_name",
    "end_station_name",
    "trip_duration_mins",
    "metadata"
    )

In [ ]:
df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(
    f"{catalog}.02_silver.jc_citibike"
)